file:
  upload-dir: /uploads

spring:
  application:
    name: back
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

custom:
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
  accessToken:
    expirationSeconds: 1200
  refreshToken:
    expirationSeconds: 604800