spring:
  application:
    name: back
  profiles:
    active: test

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
